In [22]:
import pandas as pd
import math

In [23]:
def calculate_distance_and_angle(x1, y1, x2, y2):
    distance = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
    
    angle = math.atan2(y2 - y1, x2 - x1)
    
    angle_degrees = math.degrees(angle)
    
    return distance, angle_degrees

In [24]:
df = pd.read_csv('/home/jiacheng/swarm/probing/scripts/layered_planner/recorded/original/recorded_position_0.0pi.csv')
df

,robot0_x,robot0_y,robot1_x,robot1_y,robot2_x,robot2_y,robot3_x,robot3_y,attack_drone_x,attack_drone_y
0,1.214142,1.264142,1.363294,1.494865,1.069617,1.513705,1.218858,1.762953,None,None
1,1.200000,1.250000,1.352200,1.478224,1.079131,1.496114,1.218679,1.742954,None,None
2,1.180388,1.246078,1.351666,1.458232,1.096266,1.485798,1.228439,1.725497,None,None
3,1.160589,1.248906,1.356041,1.438716,1.115667,1.480939,1.242228,1.711010,None,None
4,1.140790,1.251735,1.363476,1.420149,1.135650,1.480115,1.257366,1.697940,None,None
...,...,...,...,...,...,...,...,...,...,...
428,2.080717,-2.179514,1.955684,-1.729989,1.638474,-2.053940,1.613855,-1.670267,1.8043447590831598,-1.9035478644306665
429,2.100328,-2.183436,1.962236,-1.748886,1.644914,-2.072875,1.615131,-1.690226,1.8221824926044703,-1.908427474918248
430,2.120127,-2.186265,1.975169,-1.764142,1.655765,-2.089675,1.616109,-1.710202,1.8306523841909046,-1.9238556931975355
431,2.140005,-2.188473,1.990788,-1.776633,1.666736,-2.106397,1.619029,-1.729988,1.8417924731431983,-1.937570944778784
432,2.159883,-2.190682,2.004257,-1.791418,1.679364,-2.121907,1.623331,-1.749519,1.8541395742289188,-1.9503729116715296

In [29]:
distance1_list = []
angle1_list = []

distance2_list = []
angle2_list = []

distance3_list = []
angle3_list = []
# iterate through the rows
for index, row in df.iterrows():
    x0 = row['robot0_x']
    y0 = row['robot0_y']
    
    x1 = row['robot1_x']
    y1 = row['robot1_y']

    x2 = row['robot2_x']
    y2 = row['robot2_y']

    x3 = row['robot3_x']
    y3 = row['robot3_y']

    distance1, angle1 = calculate_distance_and_angle(x0, y0, x1, y1)
    distance2, angle2 = calculate_distance_and_angle(x0, y0, x2, y2)
    distance3, angle3 = calculate_distance_and_angle(x0, y0, x3, y3)

    distance1_list.append(distance1)
    angle1_list.append(angle1)

    distance2_list.append(distance2)
    angle2_list.append(angle2)

    distance3_list.append(distance3)
    angle3_list.append(angle3)

df['distance1'] = distance1_list
df['angle1'] = angle1_list

df['distance2'] = distance2_list
df['angle2'] = angle2_list

df['distance3'] = distance3_list
df['angle3'] = angle3_list

In [30]:
df

,robot0_x,robot0_y,robot1_x,robot1_y,robot2_x,robot2_y,robot3_x,robot3_y,attack_drone_x,attack_drone_y,distance1,angle1,distance2,angle2,distance3,angle3
0,1.214142,1.264142,1.363294,1.494865,1.069617,1.513705,1.218858,1.762953,None,None,0.274735,57.119214,0.288391,120.075753,0.498833,89.458364
1,1.200000,1.250000,1.352200,1.478224,1.079131,1.496114,1.218679,1.742954,None,None,0.274320,56.301188,0.274192,116.156062,0.493307,87.829999
2,1.180388,1.246078,1.351666,1.458232,1.096266,1.485798,1.228439,1.725497,None,None,0.272664,51.085047,0.254052,109.336899,0.481821,84.276554
3,1.160589,1.248906,1.356041,1.438716,1.115667,1.480939,1.242228,1.711010,None,None,0.272450,44.161045,0.236342,100.957133,0.469260,79.981133
4,1.140790,1.251735,1.363476,1.420149,1.135650,1.480115,1.257366,1.697940,None,None,0.279200,37.099796,0.228439,91.289432,0.461182,75.358190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,2.080717,-2.179514,1.955684,-1.729989,1.638474,-2.053940,1.613855,-1.670267,1.8043447590831598,-1.9035478644306665,0.466589,105.543556,0.459725,164.148174,0.690864,132.513612
429,2.100328,-2.183436,1.962236,-1.748886,1.644914,-2.072875,1.615131,-1.690226,1.8221824926044703,-1.908427474918248,0.455964,107.629261,0.468643,166.354244,0.691862,134.530734
430,2.120127,-2.186265,1.975169,-1.764142,1.655765,-2.089675,1.616109,-1.710202,1.8306523841909046,-1.9238556931975355,0.446319,108.952648,0.474302,168.249751,0.693304,136.633840
431,2.140005,-2.188473,1.990788,-1.776633,1.666736,-2.106397,1.619029,-1.729988,1.8417924731431983,-1.937570944778784,0.438039,109.916303,0.480333,170.161423,0.693992,138.650544
432,2.159883,-2.190682,2.004257,-1.791418,1.679364,-2.121907,1.623331,-1.749519,1.8541395742289188,-1.9503729116715296,0.428522,111.294865,0.485416,171.854723,0.694631,140.572330